### ISSUE TITLE
homescreen leaderbord suddenely no longer working

### ISSUE THREAD

**Issue by ataniphor** [ThoreBor/Anki_Leaderboard#130]
So the homescreen leader boards was working fine yesterday but today I was met with this debug window and error:
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-01-19 19:57:29

Caught exception:
Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Roaming\Anki2\addons21\41708974\Setup.py", line 322, in set_homescreen
    leaderboard_on_deck_browser()
  File "C:\Users\USERNAME\AppData\Roaming\Anki2\addons21\41708974\lb_on_homescreen.py", line 271, in leaderboard_on_deck_browser
    DB.refresh()
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-26>", line 2, in refresh
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 629, in repl
  File "aqt\deckbrowser.py", line 63, in refresh
  File "aqt\deckbrowser.py", line 115, in _renderPage
  File "aqt\deckbrowser.py", line 124, in __renderPage
  File "aqt\gui_hooks.py", line 1000, in __call__
  File "C:\Users\USERNAME\AppData\Roaming\Anki2\addons21\41708974\lb_on_homescreen.py", line 145, in on_deck_browser_will_render_content
    result.append(lb[i])
IndexError: list index out of range

Is this due to addon conflicts or something else? 
EDIT:
after some testing, managed to get table to show up by disabling "show league medals", but the "focus on user" function does not seem to be working.

**Comment by ThoreBor** [comment]
Do you only use the leaderboard on the main screen? Does opening the leaderboard first do anything?
