### ISSUE TITLE
Error when opening leaderboard

### ISSUE THREAD

**Issue by Willz7** [ThoreBor/Anki_Leaderboard#15]
Hi I recently got this error below

```
Caught exception:
Traceback (most recent call last):
  File "lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
  File "lib\site-packages\urllib3\connectionpool.py", line 376, in _make_request
  File "lib\site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
  File "lib\site-packages\urllib3\connection.py", line 386, in connect
  File "lib\site-packages\urllib3\util\ssl_.py", line 370, in ssl_wrap_socket
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\site-packages\requests\adapters.py", line 439, in send
  File "lib\site-packages\urllib3\connectionpool.py", line 719, in urlopen
  File "lib\site-packages\urllib3\util\retry.py", line 400, in increment
  File "lib\site-packages\urllib3\packages\six.py", line 734, in reraise
  File "lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
  File "lib\site-packages\urllib3\connectionpool.py", line 376, in _make_request
  File "lib\site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
  File "lib\site-packages\urllib3\connection.py", line 386, in connect
  File "lib\site-packages\urllib3\util\ssl_.py", line 370, in ssl_wrap_socket
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\William\AppData\Roaming\Anki2\addons21\41708974\__init__.py", line 20, in Main
    s = start_main()
  File "C:\Users\William\AppData\Roaming\Anki2\addons21\41708974\Leaderboard.py", line 259, in __init__
    self.dialog.setupUi(self)
  File "C:\Users\William\AppData\Roaming\Anki2\addons21\41708974\Leaderboard.py", line 117, in setupUi
    x = requests.post(url)
  File "lib\site-packages\requests\api.py", line 116, in post
  File "lib\site-packages\requests\api.py", line 60, in request
  File "lib\site-packages\requests\sessions.py", line 533, in request
  File "lib\site-packages\requests\sessions.py", line 646, in send
  File "lib\site-packages\requests\adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))
```

**Comment by ThoreBor** [comment]
Looks like you weren't connected to your wifi.

**Comment by Willz7** [comment]
Thank you
