### ISSUE TITLE
Index out of range in on_deck_browser_will_render_content

### ISSUE THREAD

**Issue by phosphene47** [ThoreBor/Anki_Leaderboard#152]
**Describe the bug**
Index out of range exception in `progress.py` when leaderboard in home screen is enabled.

**Steps to reproduce bug**
I'm really not sure. This error did not occur when I installed this addon yesterday. It started happening the next morning (the day of this report).

This does not happen when the leaderboard is opened manually with `Shift+L`. It can be reproduced consistently when synchronizing the leaderboard in home screen with `Shift+S`.

**Info**
- Anki version: 2.1.46
- Leaderboard version: 1.7.0
- OS: macOS 11.5.2

Addon config:

<img width="876" alt="image" src="https://user-images.githubusercontent.com/27663662/130884478-76facbd4-dac2-4e3f-a88f-9edbf06885c9.png">

**Additional context**
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.46 (94913ec2) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-08-26 11:13:04
Add-ons possibly involved: ⁨Leaderboard⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/progress.py", line 54, in handler
  File "aqt/main.py", line 150, in on_window_init
  File "aqt/main.py", line 245, in setupProfile
  File "aqt/main.py", line 425, in loadProfile
  File "aqt/hooks_gen.py", line 2907, in __call__
  File "/Users/phosphene47/Library/Application Support/Anki2/addons21/41708974/__init__.py", line 126, in profileHook
    leaderboard_on_deck_browser()
  File "/Users/phosphene47/Library/Application Support/Anki2/addons21/41708974/lb_on_homescreen.py", line 258, in leaderboard_on_deck_browser
    DB.refresh()
  File "aqt/deckbrowser.py", line 74, in refresh
  File "aqt/deckbrowser.py", line 143, in _renderPage
  File "aqt/deckbrowser.py", line 152, in __renderPage
  File "aqt/hooks_gen.py", line 1275, in __call__
  File "/Users/phosphene47/Library/Application Support/Anki2/addons21/41708974/lb_on_homescreen.py", line 132, in on_deck_browser_will_render_content
    result.append(lb[i])
IndexError: list index out of range
```

**Comment by phosphene47** [comment]
> Could you guys confirm that that's the issue?

I would assume that to be the case. At the time of writing this comment, the global leaderboard has enough users that this error isn't occurring anymore. However when I switch the default to country leaderboard, which presumably has less users than the global version, the error can be reproduced.

**Comment by Dreadeyee** [comment]
I think that would be valid. The global leaderboard currently has 42 users and the bug is reproducible even after disabling/enabling/restarting.
