### ISSUE TITLE
[focus on user] Error

### ISSUE THREAD

**Issue by aboali1hassona** [ThoreBor/Anki_Leaderboard#161]
when I activated a [focus on user] option. I faced this Error and I ignored this error. then when I am opening Anki, I face this error again.
{Anki 2.1.48- Windous 10}
![Screenshot (15)](https://user-images.githubusercontent.com/91283119/138427016-22051167-a9e4-43d3-a11c-c28c6e586c01.png)

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.48 (fb07bad3) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-10-22 10:33:44

Caught exception:
Traceback (most recent call last):
  File "aqt\main.py", line 299, in onOpenProfile
  File "aqt\main.py", line 425, in loadProfile
  File "aqt\hooks_gen.py", line 2945, in __call__
  File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\41708974\__init__.py", line 126, in profileHook
    leaderboard_on_deck_browser()
  File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\41708974\lb_on_homescreen.py", line 258, in leaderboard_on_deck_browser
    DB.refresh()
  File "aqt\deckbrowser.py", line 74, in refresh
  File "aqt\deckbrowser.py", line 143, in _renderPage
  File "aqt\deckbrowser.py", line 152, in __renderPage
  File "aqt\hooks_gen.py", line 1275, in __call__
  File "C:\Users\aboal\AppData\Roaming\Anki2\addons21\41708974\lb_on_homescreen.py", line 132, in on_deck_browser_will_render_content
    result.append(lb[i])
IndexError: list index out of range

**Comment by ThoreBor** [comment]
I think it was solved in #152. Either update the add-on if you haven't, or restart it.
