### ISSUE TITLE
Error is caught whenever Leaderboard is opened

### ISSUE THREAD

**Issue by Nasrrahh** [ThoreBor/Anki_Leaderboard#166]
Intel Mac | MacOS Monterey | Anki Ver. 2.1.49 | Leaderboard v2.0.0

Every time Leaderboard is opened I receive an error. I was able to signup and join a group, however. The home screen leaderboard is still visible.

(Edit: Error continues after all other addons are disabled)
Error Received:
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-12-25 23:52:22
Add-ons possibly involved: ⁨Leaderboard⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/nasrudeen.oladimeji/Library/Application Support/Anki2/addons21/41708974/__init__.py", line 26, in Main
    mw.leaderboard = start_main(season_start, season_end, current_season)
  File "/Users/nasrudeen.oladimeji/Library/Application Support/Anki2/addons21/41708974/Leaderboard.py", line 41, in __init__
    self.setupUI()
  File "/Users/nasrudeen.oladimeji/Library/Application Support/Anki2/addons21/41708974/Leaderboard.py", line 97, in setupUI
    self.load_leaderboard()
  File "/Users/nasrudeen.oladimeji/Library/Application Support/Anki2/addons21/41708974/Leaderboard.py", line 194, in load_leaderboard
    load_league(self, colors)
  File "/Users/nasrudeen.oladimeji/Library/Application Support/Anki2/addons21/41708974/League.py", line 51, in load_league
    if league_name == user_league_name and xp != 0:
UnboundLocalError: local variable 'user_league_name' referenced before assignment

**Comment by ThoreBor** [comment]
Could you please let me know what your leaderboard username is?

**Comment by Nasrrahh** [comment]
The addon works all well the day after this was opened. Thanks.
