### ISSUE TITLE
Error after choosing Leaderboard and the addon doesn't open on Anki 2.1.49

### ISSUE THREAD

**Issue by AmrAliDawoud** [ThoreBor/Anki_Leaderboard#180]
I get this error after choosing Leaderboard from the menu or pressing Shift + L
I'm using anki 2.1.49. I disabled all the other addons, but the error persist and the leaderboard doesn't appear.

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-07-05 10:59:37

Caught exception:
Traceback (most recent call last):
  File "C:\Users\makka\AppData\Roaming\Anki2\addons21\41708974\__init__.py", line 26, in Main
    mw.leaderboard = start_main(season_start, season_end, current_season)
  File "C:\Users\makka\AppData\Roaming\Anki2\addons21\41708974\Leaderboard.py", line 45, in __init__
    self.setupUI()
  File "C:\Users\makka\AppData\Roaming\Anki2\addons21\41708974\Leaderboard.py", line 106, in setupUI
    self.load_leaderboard()
  File "C:\Users\makka\AppData\Roaming\Anki2\addons21\41708974\Leaderboard.py", line 203, in load_leaderboard
    load_league(self, colors)
  File "C:\Users\makka\AppData\Roaming\Anki2\addons21\41708974\League.py", line 53, in load_league
    if league_name == user_league_name and xp != 0:
UnboundLocalError: local variable 'user_league_name' referenced before assignment
![Screenshot 2022-07-05 171102](https://user-images.githubusercontent.com/41925065/177360188-55229660-c922-4841-b599-78973612a3ec.png)

**Comment by ThoreBor** [comment]
Duplicate of #175
