### ISSUE TITLE
Error on mac when I click on leaderboard in tool bar.

### ISSUE THREAD

**Issue by AguonaAnki** [ThoreBor/Anki_Leaderboard#188]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Mac 13.0.1
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-11-10 08:03:31
Add-ons possibly involved: ⁨Leaderboard⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/agnea.shields/Library/Application Support/Anki2/addons21/41708974/__init__.py", line 26, in Main
    mw.leaderboard = start_main(season_start, season_end, current_season)
  File "/Users/agnea.shields/Library/Application Support/Anki2/addons21/41708974/Leaderboard.py", line 45, in __init__
    self.setupUI()
  File "/Users/agnea.shields/Library/Application Support/Anki2/addons21/41708974/Leaderboard.py", line 106, in setupUI
    self.load_leaderboard()
  File "/Users/agnea.shields/Library/Application Support/Anki2/addons21/41708974/Leaderboard.py", line 203, in load_leaderboard
    load_league(self, colors)
  File "/Users/agnea.shields/Library/Application Support/Anki2/addons21/41708974/League.py", line 53, in load_league
    if league_name == user_league_name and xp != 0:
UnboundLocalError: local variable 'user_league_name' referenced before assignment

**Comment by ThoreBor** [comment]
See #175
