### ISSUE TITLE
offline error

### ISSUE THREAD

**Issue by khonkhortisan** [ThoreBor/Anki_Leaderboard#19]
either a regression, or I was a different distance from being fully connected to the internet. I had it open with a blank list before, now it throws this
```
Error 
Se ha producido un error. Por favor inicia la Anki manteniendo presionadas ples teclas Mayús y la flecha hacia abajo, lo que desactivará temporalmente los extensiones que tienes instaladas. 
Si este error persiste sólo cuando tienes las extensiones activadas, utiliza Herramientas > Menú de Extensiones para deshabilitar alguna extensión y reinicia el Anki, repitiendo este proceso hasta que descubras qué extensión en concreto es la que causa el problema 
Cuando hayas descubierto la extensión que causaba el problema, por favor informa de esto a [sitio de soporte de extensiones](https://help.ankiweb.net/discussions/add-ons/). 
Información de depuración: 
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-04-02 11:05:29

Caught exception:
Traceback (most recent call last):
  File "lib\site-packages\urllib3\connection.py", line 156, in _new_conn
  File "lib\site-packages\urllib3\util\connection.py", line 61, in create_connection
  File "socket.py", line 914, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
  File "lib\site-packages\urllib3\connectionpool.py", line 376, in _make_request
  File "lib\site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
  File "lib\site-packages\urllib3\connection.py", line 334, in connect
  File "lib\site-packages\urllib3\connection.py", line 168, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x0000017111C1CA90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\site-packages\requests\adapters.py", line 439, in send
  File "lib\site-packages\urllib3\connectionpool.py", line 719, in urlopen
  File "lib\site-packages\urllib3\util\retry.py", line 436, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ankileaderboard.pythonanywhere.com', port=443): Max retries exceeded with url: /sync/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000017111C1CA90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\41708974\__init__.py", line 20, in Main
    s = start_main()
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\41708974\Leaderboard.py", line 259, in __init__
    self.dialog.setupUi(self)
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\41708974\Leaderboard.py", line 113, in setupUi
    x = requests.post(url, data = data)
  File "lib\site-packages\requests\api.py", line 116, in post
  File "lib\site-packages\requests\api.py", line 60, in request
  File "lib\site-packages\requests\sessions.py", line 533, in request
  File "lib\site-packages\requests\sessions.py", line 646, in send
  File "lib\site-packages\requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ankileaderboard.pythonanywhere.com', port=443): Max retries exceeded with url: /sync/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000017111C1CA90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

```

**Comment by ThoreBor** [comment]
Looks like a problem with your internet connection. In the next update there'll be a warning to connect to your wifi.
