### ISSUE TITLE
Error. add on not loading up.

### ISSUE THREAD

**Issue by aeonian-harshul** [ThoreBor/Anki_Leaderboard#199]
```
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-01-25 23:46:01

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.taskman", line 90, in wrapped_done
  File "aqt.operations", line 257, in wrapped_done
  File "C:\Users\soodh\AppData\Roaming\Anki2\addons21\41708974\__init__.py", line 132, in on_success
    leaderboard_on_deck_browser(self.response.json())
  File "C:\Users\soodh\AppData\Roaming\Anki2\addons21\41708974\lb_on_homescreen.py", line 273, in leaderboard_on_deck_browser
    DB.refresh()
  File "aqt.deckbrowser", line 75, in refresh
  File "aqt.deckbrowser", line 144, in _renderPage
  File "aqt.deckbrowser", line 153, in __renderPage
  File "aqt.hooks_gen", line 1444, in __call__
  File "C:\Users\soodh\AppData\Roaming\Anki2\addons21\41708974\lb_on_homescreen.py", line 127, in on_deck_browser_will_render_content
    result.append(lb[i])
IndexError: list index out of range

```

**Comment by ThoreBor** [comment]
I'm not exactly sure why this happened, but if you disable the homescreen leaderboard you won't get this error message. You could try disabling and enabling it again and syncing the leaderboard. Maybe that fixes the problem.

**Comment by aeonian-harshul** [comment]
> I'm not exactly sure why this happened, but if you disable the homescreen leaderboard you won't get this error message. You could try disabling and enabling it again and syncing the leaderboard. Maybe that fixes the problem.

tried, didn't work
