### ISSUE TITLE
Anki 2.1.24beta3 error message

### ISSUE THREAD

**Issue by AnKingMed** [ThoreBor/Anki_Leaderboard#33]
**Describe the bug**
Error message when trying to use it

**Expected behavior**
Can't use it at all

**Screenshots**

**Info**
```
Anki 2.1.24 (d3964603) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.4
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-04-05 14:16:43
Add-ons possibly involved: ⁨Leaderboard⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/Nick/Library/Application Support/Anki2/addons21/41708974/__init__.py", line 19, in Main
    s = start_main()
  File "/Users/Nick/Library/Application Support/Anki2/addons21/41708974/Leaderboard.py", line 277, in __init__
    self.dialog.setupUi(self)
  File "/Users/Nick/Library/Application Support/Anki2/addons21/41708974/Leaderboard.py", line 111, in setupUi
    streak, cards, time = Stats()
  File "/Users/Nick/Library/Application Support/Anki2/addons21/41708974/Stats.py", line 49, in Stats
    value = mw.col.db.execute("SELECT * FROM revlog WHERE cid = (?) ORDER BY id DESC",(i)).fetchall()
AttributeError: 'list' object has no attribute 'fetchall'
```

**Additional context**
love the add-on!

**Comment by ThoreBor** [comment]
This doesn't look good. The problem is probably the Anki version. I only tested it on 2.1.22 (latest stable release for windows). Seems like the add-on can't access the sqlite database. I can test it when the new version is released for windows.
